#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Tools/MCPToolBase.h"

class UMaterial;

namespace UEAIIntegration::MaterialCheckpoint
{
	constexpr const TCHAR* ProjectionIdentity = TEXT("material.authoredGraph.properties.v1");

	// Independent in-memory images are scoped to this Editor process. They are
	// separate from GraphIR projections and never replace durable Workflow recovery.
	// Authored properties exclude transient editor graphs and derived shader /
	// lightmass cache identities regenerated by native PostEditChange/Undo.
	FMCPToolResult Capture(UMaterial* Material, const FString& SnapshotId, FString& OutDigest);
	bool Contains(const FString& SnapshotId);
	void Release(const FString& SnapshotId);
	bool GetDigests(UMaterial* Material, const FString& SnapshotId, FString& OutSaved, FString& OutCurrent);
	FMCPToolResult Restore(UMaterial* Material, const FString& SnapshotId, const TSharedPtr<FJsonObject>& Params);
}
